version: org.riotkit.rkd/yaml/v1
imports:
    - rkd.standardlib.jinja

tasks:
    :entrypoint:
        description: Docker image entrypoint
        steps: |
            export RKD_UI=true

            %RKD% :setup:crontab \
                  :setup:configs \
                  :setup:wordpress-files \
                  :run:supervisor

    :run:supervisor:
        description: Run supervisor with applications
        steps: supervisord -c /etc/supervisor.conf

    :setup:crontab:
        description: Add a crontab entry
        steps: |
            echo "${AUTO_UPDATE_CRON} RKD_PATH=${RKD_PATH} rkd :update:wp" > /etc/crontabs/root

    :setup:configs:
        description: Render and copy configuration files
        steps: |
            %RKD% :j2:directory-to-directory \
                --source=/templates \
                --target=/ \
                --delete-source-files \
                --pattern="(.*).j2" \
                --copy-not-matching-files

    :setup:wordpress-files:
        description: Perform a Wordpress installation
        steps: |
            # Warning: HACK below :)
            # mock php-fpm to not start it immediately by WordPress entrypoint
            echo " >> Mock php-fpm"
            mv /usr/local/sbin/php-fpm /usr/local/sbin/php-fpm.bckp
            ln -s /bin/bash /usr/local/sbin/php-fpm

            echo " >> Installing Wordpress"
            /usr/local/bin/docker-entrypoint.sh php-fpm || exit 1

            echo " >> Cleaning up the mock"
            rm /usr/local/sbin/php-fpm
            mv /usr/local/sbin/php-fpm.bckp /usr/local/sbin/php-fpm

    :update:wp:
        description: Run a Wordpress upgrade
        become: www-data
        steps: cd /var/www/html && wp core update
