version: org.riotkit.rkd/yaml/v1
imports:
    - rkt_ciutils.boatci

build_args: &build_args
    "--version":
        help: "Wordpress version eg. 5.5"
        required: True
    "--img-version":
        help: "This docker image version"
        required: True

environment:
    GITHUB_REPOSITORY: "WordPress/WordPress"
    DEST_DOCKER_REPO: "quay.io/riotkit/wp-auto-update"
    ALLOWED_TAGS_REGEXP: '([0-9\.]+)\$'
    DOCKER_BUILD_OPTS: ""

tasks:
    :ci:build-all-versions:
        description: Build all recent Wordpress versions
        arguments:
            "--commit-msg":
                required: True

        steps: '%RKD% --no-ui :boat-ci:process --commit-message="${ARG_COMMIT_MSG}"'

    :run:
        description: Run an image
        arguments:
            <<: *build_args
        steps: docker run --rm -d --name test_wordpress -p 8000:80 quay.io/riotkit/wp-auto-update:${ARG_VERSION}-${ARG_IMG_VERSION}
